# Generated by Django 4.2.8 on 2023-12-20 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
