# Generated by Django 4.2.8 on 2023-12-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
